// <auto-generated />
using System;
using DotNetService.Infrastructure.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetService.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    [Migration("20240826065321_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DotNetService.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int?>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3827ee60-87a6-4da9-a0db-11ba0499d232"),
                            CreatedAt = new DateTime(2024, 8, 26, 13, 53, 21, 399, DateTimeKind.Local).AddTicks(7155),
                            Description = "High-performance laptop for professionals",
                            Name = "Laptop",
                            Price = 1500000,
                            Stock = 50,
                            UpdatedAt = new DateTime(2024, 8, 26, 13, 53, 21, 399, DateTimeKind.Local).AddTicks(7168)
                        },
                        new
                        {
                            Id = new Guid("b8089064-48d3-406d-8625-bb1a953c4938"),
                            CreatedAt = new DateTime(2024, 8, 26, 13, 53, 21, 399, DateTimeKind.Local).AddTicks(7259),
                            Description = "Latest model smartphone with advanced features",
                            Name = "Smartphone",
                            Price = 800000,
                            Stock = 100,
                            UpdatedAt = new DateTime(2024, 8, 26, 13, 53, 21, 399, DateTimeKind.Local).AddTicks(7260)
                        },
                        new
                        {
                            Id = new Guid("f20dee07-e193-4ceb-916b-fd796501363c"),
                            CreatedAt = new DateTime(2024, 8, 26, 13, 53, 21, 399, DateTimeKind.Local).AddTicks(7265),
                            Description = "Wireless noise-cancelling headphones",
                            Name = "Headphones",
                            Price = 300000,
                            Stock = 75,
                            UpdatedAt = new DateTime(2024, 8, 26, 13, 53, 21, 399, DateTimeKind.Local).AddTicks(7266)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
