// <auto-generated />
using System;
using DotNetService.Infrastructure.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetService.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    [Migration("20240820073103_GenerateProductSeeder")]
    partial class GenerateProductSeeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DotNetService.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int?>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0eebdf48-1e0c-4738-8913-7c8f0342f886"),
                            CreatedAt = new DateTime(2024, 8, 20, 14, 31, 2, 695, DateTimeKind.Local).AddTicks(4293),
                            Description = "High-performance laptop for professionals",
                            Name = "Laptop",
                            Price = 1500000,
                            Stock = 50,
                            UpdatedAt = new DateTime(2024, 8, 20, 14, 31, 2, 695, DateTimeKind.Local).AddTicks(4306)
                        },
                        new
                        {
                            Id = new Guid("af482c65-3638-457c-9e82-b2d840adb9f7"),
                            CreatedAt = new DateTime(2024, 8, 20, 14, 31, 2, 695, DateTimeKind.Local).AddTicks(4316),
                            Description = "Latest model smartphone with advanced features",
                            Name = "Smartphone",
                            Price = 800000,
                            Stock = 100,
                            UpdatedAt = new DateTime(2024, 8, 20, 14, 31, 2, 695, DateTimeKind.Local).AddTicks(4319)
                        },
                        new
                        {
                            Id = new Guid("dad6ca7f-b6a6-46d8-a724-870673ec6822"),
                            CreatedAt = new DateTime(2024, 8, 20, 14, 31, 2, 695, DateTimeKind.Local).AddTicks(4344),
                            Description = "Wireless noise-cancelling headphones",
                            Name = "Headphones",
                            Price = 300000,
                            Stock = 75,
                            UpdatedAt = new DateTime(2024, 8, 20, 14, 31, 2, 695, DateTimeKind.Local).AddTicks(4347)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
